apps/common/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    # INDEX
    re_path(r'^$', views.index, name='index'),
    # re_path(r'^unregister/(?P<client_pk>\d+)/(?P<workout_pk>\d+)$', views.unregister, name='unregister'),
    re_path(r'^unregister$', views.unregister, name='unregister'),

    # POSITIONS
    re_path(r'^positions/$', views.PositionListView.as_view(), name='positions'),
    re_path(r'^position/create/$', views.PositionCreate.as_view(), name='create-position'),
    re_path(r'^position/(?P<pk>\d+)/update/$', views.PositionUpdate.as_view(), name='update-position'),
    re_path(r'^position/(?P<pk>\d+)/delete/$', views.PositionDelete.as_view(), name='delete-position'),

    # PROGRAMS
    re_path(r'^programs/$', views.ProgramListView.as_view(), name='programs'),
    re_path(r'^program/(?P<pk>\d+)$', views.ProgramDetailView.as_view(), name='program-detail'),
    re_path(r'^program/create/$', views.ProgramCreate.as_view(), name='create-program'),
    re_path(r'^program/(?P<pk>\d+)/update/$', views.ProgramUpdate.as_view(), name='update-program'),
    re_path(r'^program/(?P<pk>\d+)/delete/$', views.ProgramDelete.as_view(), name='delete-program'),

    # WORKOUTS
    re_path(r'^workouts/$', views.WorkoutListView.as_view(), name='workouts'),
    re_path(r'^workout/(?P<pk>\d+)$', views.WorkoutDetailView.as_view(), name='workout-detail'),
    re_path(r'^workout/create/$', views.WorkoutCreate.as_view(), name='create-workout'),
    re_path(r'^workout/(?P<pk>\d+)/update/$', views.WorkoutUpdate.as_view(), name='update-workout'),
    re_path(r'^workout/(?P<pk>\d+)/delete/$', views.WorkoutDelete.as_view(), name='delete-workout'),

    # TRAINERS
    re_path(r'^trainers/$', views.TrainerListView.as_view(), name='trainers'),
    re_path(r'^trainer/(?P<pk>\d+)$', views.TrainerDetailView.as_view(), name='trainer-detail'),
    # re_path(r'^trainer/create/$', views.TrainerCreate.as_view(), name='create-trainer'),
    re_path(r'^trainer/(?P<pk>\d+)/update/$', views.TrainerUpdate.as_view(), name='update-trainer'),
    re_path(r'^trainer/(?P<pk>\d+)/delete/$', views.TrainerDelete.as_view(), name='delete-trainer'),

    # CLIENTS
    re_path(r'^clients/$', views.ClientListView.as_view(), name='clients'),
    re_path(r'^client/(?P<pk>\d+)/workouts$', views.client_workouts, name='client-workouts'),
    re_path(r'^client/create/$', views.ClientCreate.as_view(), name='create-client'),
    re_path(r'^client/(?P<pk>\d+)/update/$', views.ClientUpdate.as_view(), name='update-client'),
    re_path(r'^client/(?P<pk>\d+)/delete/$', views.ClientDelete.as_view(), name='delete-client'),

    re_path(r'^my-workouts/$', views.personal_workouts, name='personal-workouts'),


    ###################### ОСТАЛЬНОЕ ######################

    #
    # # PATIENTS SIGNUP
    # re_path(r'^signup/$', views.patient_signup, name='patient-signup'),
    #
    # # USERS
    # re_path(r'^users/$', views.UserListView.as_view(), name='users'),
    # re_path(r'^user/create/$', views.UserCreate.as_view(), name='create-user'),
    # re_path(r'^user/(?P<pk>\d+)/update/$', views.UserUpdate.as_view(), name='update-user'),
    # # re_path(r'^user/(?P<pk>\d+)/delete/$', views.UserDelete.as_view(), name='delete-user'),
    #
    # # SERVICES
    # re_path(r'^services/$', views.ServiceListView.as_view(), name='services'),
    # re_path(r'^service/(?P<pk>\d+)$', views.ServiceDetailView.as_view(), name='service-detail'),
    # re_path(r'^service/create/$', views.ServiceCreate.as_view(), name='create-service'),
    # re_path(r'^service/(?P<pk>\d+)/update/$', views.ServiceUpdate.as_view(), name='update-service'),
    # # re_path(r'^service/(?P<pk>\d+)/delete/$', views.ServiceDelete.as_view(), name='delete-service'),
    #
    # # DOCTORS
    # re_path(r'^doctors/$', views.DoctorListView.as_view(), name='doctors'),
    # re_path(r'^doctor/(?P<pk>\d+)$', views.DoctorDetailView.as_view(), name='doctor-detail'),
    # re_path(r'^doctor/create/$', views.DoctorCreate.as_view(), name='create-doctor'),
    # re_path(r'^doctor/(?P<pk>\d+)/update/$', views.DoctorUpdate.as_view(), name='update-doctor'),
    # # re_path(r'^doctor/(?P<pk>\d+)/delete/$', views.DoctorDelete.as_view(), name='delete-doctor'),
    #
    # # POSITIONS
    # re_path(r'^positions/$', views.PositionListView.as_view(), name='positions'),
    # re_path(r'^position/create/$', views.PositionCreate.as_view(), name='create-position'),
    # re_path(r'^position/(?P<pk>\d+)/update/$', views.PositionUpdate.as_view(), name='update-position'),
    # # re_path(r'^position/(?P<pk>\d+)/delete/$', views.PositionDelete.as_view(), name='delete-position'),
    #
    # # SPECIALIZATIONS
    # re_path(r'^specializations/$', views.SpecializationListView.as_view(), name='specializations'),
    # re_path(r'^specialization/create/$',
    #         views.SpecializationCreate.as_view(), name='create-specialization'),
    # re_path(r'^specialization/(?P<pk>\d+)/update/$',
    #         views.SpecializationUpdate.as_view(), name='update-specialization'),
    # # re_path(r'^specialization/(?P<pk>\d+)/delete/$',
    # #         views.SpecializationDelete.as_view(), name='delete-specialization'),
    #
    # # PATIENTS
    # re_path(r'^patients/$', views.PatientListView.as_view(), name='patients'),
    # re_path(r'^patient/(?P<pk>\d+)/personal/$', views.patient_personal, name='patient-personal'),
    # re_path(r'^patient/create/$', views.PatientCreate.as_view(), name='create-patient'),
    # re_path(r'^patient/(?P<pk>\d+)/update/$', views.PatientUpdate.as_view(), name='update-patient'),
    # # re_path(r'^patient/(?P<pk>\d+)/delete/$', views.PatientDelete.as_view(), name='delete-patient'),
    #
    # # EMPLOYEES
    # re_path(r'^employees/$', views.EmployeeListView.as_view(), name='employees'),
    # re_path(r'^employee/create/$', views.EmployeeCreate.as_view(), name='create-employee'),
    # re_path(r'^employee/(?P<pk>\d+)/update/$', views.EmployeeUpdate.as_view(), name='update-employee'),
    # # re_path(r'^employee/(?P<pk>\d+)/delete/$', views.EmployeeDelete.as_view(), name='delete-employee'),
    #
    # # PERSONAL
    # re_path(r'^personal/$', views.personal, name='personal'),
    #
    # # APPOINTMENTS
    # re_path(r'^personal/appointment/(?P<pk>\d+)/$', views.AppointmentDetailView.as_view(), name='appointment-detail'),
    # re_path(r'^personal/appointment/create/$', views.AppointmentCreate.as_view(), name='create-appointment'),
    # re_path(r'^personal/appointment/(?P<pk>\d+)/update/$', views.AppointmentUpdate.as_view(),
    #         name='update-appointment'),
    #
    # # MEDICAL TESTS
    # re_path(r'^personal/medicaltest/(?P<pk>\d+)/$', views.MedicalTestDetailView.as_view(), name='medicaltest-detail'),
    # re_path(r'^personal/medicaltest/create/$', views.MedicalTestCreate.as_view(), name='create-medicaltest'),
    # re_path(r'^personal/medicaltest/(?P<pk>\d+)/update/$', views.MedicalTestUpdate.as_view(),
    #         name='update-medicaltest'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.common.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/common/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse


class Position(models.Model):
    name = models.CharField(max_length=255, help_text="Название должности")
    salary = models.IntegerField(null=True, blank=False)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class FitnessUser(models.Model):
    SEX = (
        ("м", "Мужской"),
        ("ж", "Женский"),
        ("н", "Не указано"),
    )

    user = models.OneToOneField(User, on_delete=models.RESTRICT, default=None)
    full_name = models.CharField(max_length=255)
    gender = models.CharField(max_length=1, choices=SEX, blank=True, default="н")
    phone_number = models.CharField(max_length=11, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ["full_name"]

    def __str__(self):
        return "Пользователь " + self.user.username


class Client(models.Model):
    fitness_user = models.OneToOneField(FitnessUser, on_delete=models.RESTRICT)
    has_subscription = models.BooleanField()

    class Meta:
        ordering = ["fitness_user__full_name"]

    def __str__(self):
        return "Клиент " + self.fitness_user.full_name


class Employee(models.Model):
    fitness_user = models.OneToOneField(FitnessUser, on_delete=models.RESTRICT)
    position = models.ForeignKey(Position, on_delete=models.RESTRICT)
    employment_history_book_id = models.CharField(max_length=7, null=True, blank=True)

    class Meta:
        ordering = ["position", "fitness_user__full_name"]

    def __str__(self):
        return f"{self.position} {self.fitness_user.full_name}"


class Trainer(models.Model):
    fitness_employee = models.OneToOneField(Employee, on_delete=models.RESTRICT)
    description = models.CharField(max_length=1000, null=True, blank=True)

    def __str__(self):
        return f"Тренер {self.fitness_employee.fitness_user.full_name}"

    def get_absolute_url(self):
        return reverse("trainer-detail", args=(str(self.id)))


class Program(models.Model):
    name = models.CharField(max_length=500, null=False, blank=False, unique=True)
    description = models.CharField(max_length=1000, null=True, blank=True)
    cost = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"Программа {self.name}"

    def get_absolute_url(self):
        return reverse("program-detail", args=(str(self.id)))


class Workout(models.Model):
    workout_name = models.CharField(max_length=500, null=False, blank=False)
    workout_description = models.CharField(max_length=1000, null=True, blank=True)
    program = models.ForeignKey(Program, on_delete=models.RESTRICT)
    trainer = models.ForeignKey(Trainer, on_delete=models.SET_NULL, null=True, blank=True)
    workout_datetime = models.DateTimeField(null=True, blank=True)
    client = models.ManyToManyField(Client, blank=True)

    class Meta:
        ordering = ["workout_datetime", "program", "workout_name"]

    def __str__(self):
        return f"Занятие '{self.workout_name}'. Программа {self.program.name}"


def create_group_links(instance, created, **kwargs):
    if created and instance.position.name == 'Тренер':
        Trainer.objects.create(fitness_employee=instance, description='')


post_save.connect(create_group_links, sender=Employee)

apps/common/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.models import User

from .models import Workout


class WorkoutForm(forms.ModelForm):
    class Meta:
        fields = "__all__"
        model = Workout
        workout_datetime = forms.DateTimeField(widget=forms.TextInput(attrs={'type': 'datetime'}))
# class PatientSignUpForm(UserCreationForm):
#     GENDER_LIST = (
#         ("н", "не указано"),
#         ("м", "мужской"),
#         ("ж", "женский"),
#     )
#
#     first_name = forms.CharField(max_length=50, help_text="Имя")
#     last_name = forms.CharField(max_length=50, help_text="Фамилия")
#     patronymic = forms.CharField(max_length=50, help_text="Отчество")
#     gender = forms.ChoiceField(choices=GENDER_LIST, help_text="Пол")
#     phone_number = forms.CharField(
#         max_length=15, required=False, help_text="Номер телефона"
#     )
#     address = forms.CharField(
#         max_length=255, required=False, help_text="Адрес фактического проживания"
#     )
#     passport_id = forms.CharField(
#         max_length=11,
#         required=False,
#         help_text="Паспортные данные (в виде 0000-000000)",
#     )
#     birth_date = forms.DateField(
#         required=False,
#         help_text="Дата рождения",
#         widget=forms.DateInput(attrs={"type": "date"}),
#     )
#     email = forms.EmailField(max_length=254, help_text="Электронная почта")
#
#     class Meta:
#         model = User
#         fields = (
#             "username",
#             "last_name",
#             "first_name",
#             "patronymic",
#             "gender",
#             "birth_date",
#             "address",
#             "passport_id",
#             "phone_number",
#             "email",
#             "password1",
#             "password2",
#         )
#
#
# class PatientForm(forms.ModelForm):
#     class Meta:
#         model = Patient
#         exclude = ["user"]
#
#
# class EmployeeForm(forms.ModelForm):
#     class Meta:
#         model = Employee
#         exclude = ["user"]
#
#
# class UserUpdateForm(UserChangeForm):
#     password = None
#
#     class Meta:
#         model = User
#         exclude = ["password", "last_login", "is_active", "date_joined"]
#
#
# class AppointmentCreateForm(forms.ModelForm):
#     class Meta:
#         model = Appointment
#         exclude = [
#             "patient_complaints",
#             "anamnesis",
#             "examination_result",
#             "diagnosis",
#             "recommendations",
#         ]
#
#
# class MedicalTestCreateForm(forms.ModelForm):
#     class Meta:
#         model = MedicalTest
#         exclude = ["result"]

templates/common/client_create.html
{% extends 'base.html' %}
{% block title %} Клиенты {% endblock %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="p-3" style="font-size: xxx-large">Добавление данных клиента</h1>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      {{ field|as_crispy_field }}
      {% for error in field.errors %}
        {{ error|as_crispy_errors }}
      {% endfor %}
    {% endfor %}
    <div class="input-group">
      <div class="input-group-btn mr-3">
        <a class="btn btn-primary" href="{% url 'clients' %}">Назад</a>
      </div>
      <input class="btn btn-primary" type="submit" value="Добавить" style="margin-bottom: 1em;">
    </div>
  </form>
{% endblock %}

templates/common/client_list.html
{% extends 'base.html' %}
{% block title %} Клиенты {% endblock %}
{% block content %}
    <div class="d-flex justify-content-between align-items-center">
        <h1 class="p-3" style="font-size: xxx-large">Клиенты</h1>
        {% for group in request.user.groups.all %}
            {% if group.name == 'Администратор' %}
                <a class="" href="{% url 'create-client' %}">Добавить нового клиента</a>
            {% endif %}
        {% endfor %}
    </div>
    <hr class="mt-0 mb-4"/>
    <div class="list-group list-group-flush">
        {% for client in client_list %}
            <div class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                <div>{{ client }}</div>
                <div>
                    <div style="margin-right: 1em;"><a href="{% url 'client-workouts' pk=client.id %}">Список
                        занятий</a>
                    </div>
                    {% for group in request.user.groups.all %}
                        {% if group.name == 'Администратор' %}
                            <div style="margin-right: 1em;"><a href="{% url 'update-client' pk=client.id %}">Изменить</a>
                            </div>
                            <form class="p-0 m-0" method="POST" action="{% url "delete-client" pk=client.id %}">
                                {% csrf_token %}
                                <button class="btn btn-link btn-primary p-0 m-0" type="submit"
                                        style="font-size: medium; font-weight: 200; text-transform: capitalize;">Удалить
                                </button>
                            </form>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/common/client_workouts.html
{% extends 'base.html' %}
{% block title %} Клиент {% endblock %}
{% block content %}
    {% for group in request.user.groups.all %}
        {% if group.name == 'Администратор' or group.name == 'Тренер' %}
            <div class="d-flex justify-content-start align-items-start">
                <h1 class="pl-3 pb-0">Занятия клиента</h1>
                <h3 class="pl-3 pb-0 pt-0">{{ client.fitness_user.full_name }}</h3>
            </div>
        {% elif group.name == 'Клиент' %}
            <h1 class="pl-3 pb-0 pt-0">Мои занятия</h1>
        {% endif %}
    {% endfor %}
    <hr class="mt-1 mb-4"/>
    <div class="d-flex">
        <div class="list-group list-group-flush col-sm-6" style="border-right: 1px solid rgba(91,91,91,0.82)">
            <div class="list-group-item-heading d-flex justify-content-between align-items-center">
                <h2 class="p-2">Предстоящие занятия</h2>
            </div>
            {% for workout in workouts %}
                {% if workout.workout_datetime >= current_datetime %}
                    <div class="list-group-item border-0 list-group-item-action d-flex justify-content-between align-items-center">
                        <div>
                            <div>{{ workout }}</div>
                            <div><strong>Дата и время занятия: {{ workout.workout_datetime|date:'d.m.Y H:i' }}</strong>
                            </div>
                        </div>
                        <div>
                            <div style="margin-right: 1em;"><a
                                    href="{% url 'workout-detail' pk=workout.id %}">Подробнее</a>
                            </div>
                            {% for group in request.user.groups.all %}
                                {% if group.name == 'Администратор' %}
                                    <form class="p-0 m-0" method="POST"
                                          action="{% url "unregister" %}">
                                        <input type="hidden" name="client_pk" value="{{ client.id }}"/>
                                        <input type="hidden" name="workout_pk" value="{{ workout.id }}"/>
                                        <input type="hidden" name="redirect" value="client"/>
                                        {% csrf_token %}
                                        <button class="btn btn-link btn-primary p-0" type="submit"
                                                style="font-size: medium; font-weight: 200; text-transform: initial;">
                                            Отменить запись
                                        </button>
                                    </form>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="list-group list-group-flush col-sm-6">
            <div class="list-group-item-heading d-flex justify-content-between align-items-center">
                <h2 class="p-2">Прошедшие занятия</h2>
            </div>
            {% for workout in workouts %}
                {% if workout.workout_datetime <= current_datetime %}
                    <div class="list-group-item border-0 list-group-item-action d-flex justify-content-between align-items-center">
                        <div>
                            <div>{{ workout }}</div>
                            <div><strong>Дата и время занятия: {{ workout.workout_datetime|date:'d.m.Y H:i' }}</strong>
                            </div>
                        </div>
                        <div>
                            <div style="margin-right: 1em;"><a
                                    href="{% url 'workout-detail' pk=workout.id %}">Подробнее</a>
                            </div>
                            {% for group in request.user.groups.all %}
                                {% if group.name == 'Администратор' %}
                                    <form class="p-0 m-0" method="POST"
                                          action="{% url "unregister" %}">
                                        <input type="hidden" name="client_pk" value="{{ client.id }}"/>
                                        <input type="hidden" name="workout_pk" value="{{ workout.id }}"/>
                                        <input type="hidden" name="redirect" value="client"/>
                                        {% csrf_token %}
                                        <button class="btn btn-link btn-primary p-0" type="submit"
                                                style="font-size: medium; font-weight: 200; text-transform: initial;">
                                            Отменить запись
                                        </button>
                                    </form>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    {#    <div class="list-group list-group-flush">#}
    {#        {% for workout in workouts %}#}
    {#            <div class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">#}
    {#                <div>#}
    {#                    <div>{{ workout }}</div>#}
    {#                    <div><strong>Дата и время занятия: {{ workout.workout_datetime|date:'d.m.Y H:i' }}</strong></div>#}
    {#                </div>#}
    {#                <div>#}
    {#                    <div style="margin-right: 1em;"><a href="{% url 'workout-detail' pk=workout.id %}">Подробнее</a>#}
    {#                    </div>#}
    {#                    {% for group in request.user.groups.all %}#}
    {#                        {% if group.name == 'Администратор' %}#}
    {#                            <form class="p-0 m-0" method="POST"#}
    {#                                  action="{% url "unregister" %}">#}
    {#                                <input type="hidden" name="client_pk" value="{{ client.id }}"/>#}
    {#                                <input type="hidden" name="workout_pk" value="{{ workout.id }}"/>#}
    {#                                <input type="hidden" name="redirect" value="client"/>#}
    {#                                {% csrf_token %}#}
    {#                                <button class="btn btn-link btn-primary p-0" type="submit"#}
    {#                                        style="font-size: medium; font-weight: 200; text-transform: initial;">Отменить#}
    {#                                    запись#}
    {#                                </button>#}
    {#                            </form>#}
    {#                        {% endif %}#}
    {#                    {% endfor %}#}
    {#                </div>#}
    {#            </div>#}
    {#        {% endfor %}#}
    {#    </div>#}
{% endblock %}

templates/common/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} Главная {% endblock title %}
{% block content %}
    <div>
        <h2 class="p-3">О клубе</h2>
        <ul class="list-group list-group-flush col-sm-3">
            <li class="list-group-item d-flex align-items-center border-top-0">
                Групповые программы <span
                    class="ml-4 badge badge-primary badge-pill">{{ fitness_program_amount }}</span>
            </li>
            <li class="list-group-item d-flex align-items-center">
                Тренеры <span class="ml-4 badge badge-primary badge-pill">{{ trainer_amount }}</span>
            </li>
        </ul>
    </div>
    <div>
        <div class="d-flex justify-content-evenly align-items-center">
            <h2 class="p-3">Популярные программы</h2>
            <a class="" href="{% url 'programs' %}">Смотреть все</a>
        </div>
        <div class="card-deck">
            {% for program in fitness_program_list %}
                <div class="card mt-1">
                    <h5 class="card-header"><b>{{ program.name }}</b></h5>
                    <div class="card-body">
                        <p class="card-text text-truncate"><strong>Описание:</strong> {{ program.description }}</p>
                        <p class=card-text"><strong>Стоимость занятия:</strong> {{ program.cost }} руб.</p>
                    </div>
                    <div class="card-footer d-flex justify-content-center">
                        <a class="btn btn-primary" href="{% url 'program-detail' pk=program.id %}">Подробнее</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div>
        <div class="d-flex justify-content-evenly align-items-center">
            <h2 class="p-3">Наши тренеры</h2>
            <a class="" href="{% url 'trainers' %}">Смотреть все</a>
        </div>
        <div class="card-deck">
            {% for trainer in trainer_list %}
                <div class="card mt-1">
                    <h5 class="card-header"><b>{{ trainer.fitness_employee.fitness_user.full_name }}</b></h5>
                    <div class="card-body">
                        <p class="card-text text-truncate"><strong>Описание:</strong> {{ trainer.description }}</p>
                    </div>
                    <div class="card-footer d-flex justify-content-center">
                        <a class="btn btn-primary" href="{% url 'trainer-detail' pk=trainer.id %}">Подробнее</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div>
        <h2 class="pt-3 pl-3 pr-3 pb-0 mb-0">Контакты</h2>
        <ul class="list-group list-group-flush col-sm-5">
            <li class="list-group-item border-0"><b>Запись на занятия:</b> <a href="tel:88005553535">89771335435</a>
            </li>
            <li class="list-group-item border-0"><b>Наш адрес:</b> г. Махачкала, ул. Гагарина, д. 3</li>
        </ul>
    </div>
{% endblock %}

templates/common/position_create.html
{% extends 'base.html' %}
{% block title %} Должности {% endblock %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="p-3" style="font-size: xxx-large">Добавление должности</h1>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      {{ field|as_crispy_field }}
      {% for error in field.errors %}
        {{ error|as_crispy_errors }}
      {% endfor %}
    {% endfor %}
    <div class="input-group">
      <div class="input-group-btn mr-3">
        <a class="btn btn-primary" href="{% url 'positions' %}">Назад</a>
      </div>
      <input class="btn btn-primary" type="submit" value="Добавить" style="margin-bottom: 1em;">
    </div>
  </form>
{% endblock %}

templates/common/position_list.html
{% extends 'base.html' %}
{% block title %} Должности {% endblock %}
{% block content %}
    <div class="d-flex justify-content-between align-items-center">
        <h1 class="p-3" style="font-size: xxx-large">Должности</h1>
        {% for group in request.user.groups.all %}
            {% if group.name == 'Администратор' %}
                <a class="" href="{% url 'create-position' %}">Добавить новую должность</a>
            {% endif %}
        {% endfor %}
    </div>
    <hr class="mt-0 mb-4"/>
    <div class="list-group list-group-flush">
        {% for position in position_list %}
            <div class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                <div class="">{{ position }}</div>
                {% for group in request.user.groups.all %}
                    {% if group.name == 'Администратор' %}
                        <div>
                            <div style="margin-right: 1em;"><a href="{% url 'update-position' pk=position.id %}">Изменить</a>
                            </div>
                            <form class="p-0 m-0" method="POST" action="{% url "delete-position" pk=position.id %}">
                                {% csrf_token %}
                                <button class="btn btn-link btn-primary p-0" type="submit"
                                        style="font-size: medium; font-weight: 200; text-transform: capitalize;">Удалить
                                </button>
                            </form>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/common/position_update.html
{% extends 'base.html' %}
{% block title %} Должности {% endblock %}
{% load crispy_forms_filters %}

{% block content %}
    <h1 class="p-3" style="font-size: xxx-large">Изменение должности</h1>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            {{ field|as_crispy_field }}
            {% for error in field.errors %}
                {{ error|as_crispy_errors }}
            {% endfor %}
        {% endfor %}
        <div class="input-group">
            <div class="input-group-btn mr-3">
                <a class="btn btn-primary" href="{% url 'positions' %}">Назад</a>
            </div>
            <input class="btn btn-primary" type="submit" value="Изменить" style="margin-bottom: 1em;">
        </div>
    </form>
{% endblock %}